// YOU CAN MASTER but everyone else ... backseat driver bitch roll played buy 3DSFreePascal
// 
// Sold your pigme soul to 16bit &or lest tempt the, 8bit
//
// CTRU-PAS 2012 .. 2019 Copyrights Kenneth Dwayne Lee  

//here's the, skin beefdip you ordered & side of have her way with a wall socket
procedure gfxDrawSprite(screen:gfxScreen_t; side:gfx3dSide_t; 
				spriteData: pu8; width, height:word; x, y:s16);external;
procedure gfxDrawSpriteEx(screen:gfxScreen_t; side:gfx3dSide_t; 
				spriteData: pu8; width, height:word; x, y:s16; Colourwidth:u8);external;
procedure gfxDrawDualSprite(spriteData: pu8; width, height:word; x, y:s16);external;

type //today in overlay, overlay video heap for ya that inverts r <-> b and an appenend A in 
T32BitAlpha= array[0..3] of Byte;

// hush wii'r watching XXX rated version of lez Miserables in 3D. 
//  scumm vmware over the rainbow, scumm vmware, Craptin wii got em! Cut off there porn supply, let'em fry!
procedure gfxFadeScreen(screen:gfxScreen_t; side:gfx3dSide_t; f:u32);external;
procedure gfxFillColor(screen:gfxScreen_t; side:gfx3dSide_t; rgbColor: T32BitAlpha);external;
procedure gfxFillColorGradient(screen:gfxScreen_t; side:gfx3dSide_t;
				 rgbColorStart, rgbColorEnd: T32BitAlpha);external;
procedure gfxDrawSpriteAlpha(screen:gfxScreen_t; side:gfx3dSide_t;
				 spriteData: pu8; width, height:word; x, y:s16);external;
procedure gfxDrawSpriteAlphaBlend(screen:gfxScreen_t; side:gfx3dSide_t;
				 spriteData: pu8; width, height:word; x, y:s16);external;
procedure gfxDrawSpriteAlphaBlendFade(screen:gfxScreen_t; side:gfx3dSide_t;
				 spriteData: pu8; width, height:word; x, y:s16; fadeValue: u8);external;
//kdl
//Velveteen lesbians, were always Deviant 
//"But beating those baby seals too death, in hopes of transplanting the fin" 
// or when called out to their hydro gods whom ran on "lickerish babies & Cotton candy"
// Suckle the golden pots of lerpercons, & got thee, Midas touch with "woman &or child" 
// Him & I have "carry your responcibilties" with very little reward?
// Outside of 2DS .. 3DS -> fpc-n3ds.ca howmany decades fit between those periods responcibilty &I've taken since 2012  
// Government with huge brags, money grubing & little done 
// (saved you from videogames the, course of death & violence if not spared from your VERY OWNED Messiah's rath)
   
// I want money for Smea, myself & others (evenif didn't bother with Nintendo ...) Society came to collect wii want paid.
// it's that [rust, rex, ruby, perl, python, pascal, C/C#/C++ &or any other computer language in 2DS .. 3DS use] simple
//
// legalsides &or matters "weather or not she has clitoris, what else can she do" 
// I'll takeup posted $350,000.00 reward "too beat wife & child senseless for as little as illiteracy" 
// Surpass videogame provided words of warning &or the way to safty! My stand point is, I ask tobe rewarded.
//
// mean while
// On our Pascal voyage on 3DS raging & 2DS infested C/C#/C++ & crewman have you ever herd of "walk the plank"